### Create a new message
POST http://localhost:8080/v1/messages
Content-Type: application/json

{
  "body": "ENVIO LOGANDO DEBUG",
  "userId": "26c631c3-57b5-41c7-beb9-bc44de1f53f7",
  "email": "yan.figueiredo@softawii.com.br",
  "scheduledTime": "2025-11-13T10:00:00Z"
}

### Get message by ID (replace with actual ID from create response)
GET http://localhost:8080/v1/messages/6c95becc-e409-4b3e-9154-28b21c904877

### Get all messages (default pagination)
GET http://localhost:8080/v1/messages

### Get all messages (custom pagination - page 0, size 5)
GET http://localhost:8080/v1/messages?page=0&size=10

### Get all messages (page 1, size 10)
GET http://localhost:8080/v1/messages?page=1&size=10